@startmindmap
* Project Run
** Knownledge Management
*** Github
*** VSCode
*** Markdown
*** PlantUML
*** LICEcap
** Software
*** Omniverse
*** Houdini
*** Photoshop
*** Blender
** Hardware
*** RTX
*** 6 Displays
*** 3D Mouse
*** VR
@endmindmap